# Generated by Django 5.1.4 on 2026-06-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.CharField(choices=[('MEDITATION', 'Meditation'), ('BREATHWORK', 'Breathwork'), ('YOGA', 'Yoga'), ('SOUND', 'Sound healing'), ('COACHING', 'Coaching')], default='MEDITATION', max_length=16),
        ),
        migrations.AddField(
            model_name='session',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='session',
            name='location',
            field=models.CharField(blank=True, default='Online', max_length=160),
        ),
        migrations.AddField(
            model_name='session',
            name='mode',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('IN_PERSON', 'In person')], default='ONLINE', max_length=16),
        ),
    ]
